const { Client } = require('pg');

// Supabase Database Connection String
// 형식: postgresql://postgres:[비밀번호]@db.[프로젝트참조ID].supabase.co:5432/postgres
const connectionString = process.env.DATABASE_URL || 'YOUR_SUPABASE_POSTGRES_CONNECTION_STRING';

if (connectionString === 'YOUR_SUPABASE_POSTGRES_CONNECTION_STRING') {
    console.error("Error: 'YOUR_SUPABASE_POSTGRES_CONNECTION_STRING' 부분을 본인의 Supabase PostgreSQL 연결 문자열로 변경해 주세요.");
    console.log("\n[연결 문자열 확인 방법]:");
    console.log("1. Supabase 대시보드 진입 (supabase.com)");
    console.log("2. 프로젝트 선택 -> 좌측 하단 'Project Settings' 클릭");
    console.log("3. 'Database' 탭 선택 -> 'Connection String' 영역 확인");
    console.log("4. URI 형식을 복사한 뒤 본인의 데이터베이스 비밀번호를 대입해 입력해 주세요.");
    process.exit(1);
}

const client = new Client({
    connectionString,
    ssl: {
        rejectUnauthorized: false // Supabase SSL connection requirement
    }
});

async function runMigration() {
    try {
        console.log("1. Supabase PostgreSQL 데이터베이스에 연결 중...");
        await client.connect();
        console.log("✔ 데이터베이스 연결 성공!");

        console.log("\n2. 'consulting_inquiries' 테이블 생성 중...");
        await client.query(`
            CREATE TABLE IF NOT EXISTS consulting_inquiries (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name text NOT NULL,
                phone text NOT NULL,
                email text,
                inquiry_type text NOT NULL,
                message text NOT NULL,
                status text DEFAULT 'pending',
                created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
            );
        `);
        console.log("✔ 테이블 생성이 완료되었습니다!");

        console.log("\n3. RLS (Row Level Security) 및 보안 정책(Policy) 구성 중...");
        await client.query(`
            -- RLS 활성화 (보안 제어)
            ALTER TABLE consulting_inquiries ENABLE ROW LEVEL SECURITY;
            
            -- 기존 정책 존재 시 삭제 후 재구성
            DROP POLICY IF EXISTS "Allow public insert access" ON consulting_inquiries;
            
            -- 비로그인 익명 방문자(anon)도 문의 작성(INSERT)만 가능하도록 허용하는 정책 추가
            CREATE POLICY "Allow public insert access" 
            ON consulting_inquiries 
            FOR INSERT 
            TO anon 
            WITH CHECK (true);
        `);
        console.log("✔ RLS 보안 정책 적용 완료! (비로그인 사용자도 문의 등록이 가능합니다)");
        console.log("\n🎉 Supabase 데이터베이스 세팅이 성공적으로 완료되었습니다! 🎉");

    } catch (error) {
        console.error("\n❌ 데이터베이스 세팅 중 오류가 발생했습니다:");
        console.error(error.message);
    } finally {
        await client.end();
        console.log("연결이 종료되었습니다.");
    }
}

runMigration();
