const { Client } = require('pg');

module.exports = async (req, res) => {
    // Supabase direct connection string (resolved via Vercel's IPv6 networks)
    const connectionString = 'postgresql://postgres:tag04120115@db.lpxowhmcbeaszaiehxdv.supabase.co:5432/postgres';
    
    const client = new Client({
        connectionString,
        ssl: {
            rejectUnauthorized: false
        }
    });

    try {
        console.log("Connecting to Supabase database...");
        await client.connect();
        console.log("Connected successfully!");

        console.log("Creating table 'consulting_inquiries'...");
        await client.query(`
            CREATE TABLE IF NOT EXISTS consulting_inquiries (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name text NOT NULL,
                phone text NOT NULL,
                email text,
                inquiry_type text NOT NULL,
                message text NOT NULL,
                status text DEFAULT 'pending',
                created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
            );
        `);

        console.log("Applying RLS policy...");
        await client.query(`
            ALTER TABLE consulting_inquiries ENABLE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS "Allow public insert access" ON consulting_inquiries;
            CREATE POLICY "Allow public insert access" 
            ON consulting_inquiries 
            FOR INSERT 
            TO anon 
            WITH CHECK (true);
        `);

        await client.end();
        
        return res.status(200).json({
            success: true,
            message: "Supabase table 'consulting_inquiries' and RLS policies created successfully! 🎉"
        });

    } catch (error) {
        console.error("Database migration error:", error);
        return res.status(500).json({
            success: false,
            error: error.message
        });
    }
};
